CV_NAME = CV_FR_Paul_Chauveau.pdf
CAPA_NAME = capability_Paul_Chauveau.pdf

all: capa

capa:
	@cd src && pdflatex capability.tex
	@mv src/capability.pdf $(CAPA_NAME)

resume:
	@cd src && pdflatex resume.tex
	@mv src/resume.pdf $(CV_NAME)

clean:
	@cd src && rm -f *.aux *.out *.log *.pdf
	@rm -f $(CV_NAME) $(CAPA_NAME)
 
help:
	@echo "Usage:"
	@echo -e " make [all]\t\tBuild capability"
	@echo -e " make capa\t\tBuild capability"
	@echo -e " make resume\t\tBuild resume"
	@echo -e " make clean\t\tRemove all files generated by make"
	@echo -e " make help\t\tDisplay this help"

.PHONY: all capa resume clean help