NAME = CV_FR_Paul_Chauveau.pdf

all: resume

resume:
	@cd src && pdflatex resume.tex
	@mv src/resume.pdf $(NAME)

clean:
	@cd src && rm -f *.aux *.out *.log *.pdf
	@rm -f $(NAME)

help:
	@echo "Usage:"
	@echo -e " make [all]\t\tBuild resume"
	@echo -e " make resume\t\tBuild resume"
	@echo -e " make clean\t\tRemove all files generated by make"
	@echo -e " make help\t\tDisplay this help"

.PHONY: all resume clean help